# Generated by Django 4.0 on 2022-10-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0009_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['dt_created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dt_created']},
        ),
    ]
